name: Daily Article Delivery

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 PM UTC every day
  workflow_dispatch:  # Allow manual triggering

jobs:
  deliver-article:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run article delivery
      env:
        TELEGRAM_BOT_TOKEN: ${{ 7929490695:AAEf81hJYm6ShnZO2eBTgaGOp9LV4G-roZE }}
        TELEGRAM_CHAT_ID: ${{ secrets.RadiAiBot }}
      run: |
        python main.py
